### ISSUE TITLE
S3 Buckets with example IAM policy and encryption

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#112]
Need an S3 Bucket in-place for ITHC 1.

- [x] S3 Bucket in with example IAM policy
- [x] SSE enabled on the bucket and all objects
- [x] Versioning enabled
- [x] One S3 buckets in Peering
- [x] Four S3 buckets in Apps
- [x] One VPC endpoints in Apps, data and logs
- [x] One VPC endpoints in Peering, data and logs to Apps bucket
- [x] One VPC endpoint in OPS, logs to Apps bucket
- [x] Connections to S3 buckets with corresponding VPC endpoints
- [x] Add KMS permissions to nonprod user
- [x] All buckets deployed and operational

**Comment by david-wirelab** [comment]
Blocked by https://github.com/UKHomeOffice/dq-aws-transition/issues/70
