### ISSUE TITLE
Configure routing between VPCs and verify connectivity using the test instances

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#120]
Configure route tables in each VPC and add appropriate route entries for full mesh.

- [x] Apps
  - [x] Connectivity tester check target success 
Prerequisites for Apps:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input 
- [x] Ops
  - [x] Connectivity tester check target success 
Prerequisites for Ops:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input 
- [x] Peering
  - [x] Connectivity tester check target success 
Prerequisites for Peering:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input 
- [x] ACP Prod
  - [x] Connectivity tester check target success 
Prerequisites for ACP Prod:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input 
- [x] ACP VPN
  - [x] Connectivity tester check target success 
Prerequisites for ACP VPN:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input 
- [x] ACP CICD
  - [x] Connectivity tester check target success 
Prerequisites for ACP CICD:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input 
- [x] ACP OPS
  - [x] Connectivity tester check target success 
Prerequisites for ACP OPS:
    - [x] VPC Peering id as input
    - [x] Route table CIDR blocks as input

**Comment by david-wirelab** [comment]
2 options.

- Push down subnet CIDRs along with vpc peering id to child modules.

Pass CIDRs all down in a list/map - perhaps map is actually better as then there's no need for splitting the list - and then ingest them to the route table as individual route entries.
With list the order matters, with map not so much.
Pass peering ID as a variable and import to route entry.

Pro: infra module is lean only hosts two additional variable and extra config is down within the actual repo config. 
Con: passing lots of data downstream from root, lack of visibility/admin option at infra layer, config overhead.

- Route at infra level and pass down route table id to the subnet and any other consumers

Export GW ids from VPCs to modules.  Create a route table resource at infra within vpc peering config so the connection ID can be referenced easily (reference module too). Import GW ID and vpc connection ID along with CIDRs from other modules.
Export RT ID and pass it down to the child and grandchild modules subnets for reference.

Pro: easy to see config at infra layer, only a single variable to pass down to each VPC (for now)
Con: messy at infra layer (create module?)

**Comment by david-wirelab** [comment]
Agreed on going with the first option to keep modules self contained.

**Comment by chrisns** [comment]
blocked by #136

**Comment by david-wirelab** [comment]
closing case - opened separate one for RDS https://github.com/UKHomeOffice/dq-aws-transition/issues/144
