### ISSUE TITLE
Deploy Jira Software v7 Docker Image on ACP/DSP Kube8 cluster

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#124]
Deploy Jira Software v7 Docker Image on ACP/DSP Kube8 cluster.
 
Docker image repo:
https://gitlab.digital.homeoffice.gov.uk/docker/docker-jira/blob/master/Dockerfile

k8s deployment 
https://gitlab.digital.homeoffice.gov.uk/Devops/kube-jira/tree/master

- [ ] Deploy Jira Software v7 Docker Image on ACP/DSP Kube8 cluster

**Comment by chrisns** [comment]
dupe of #125
