### ISSUE TITLE
Deploy Jira in DQ ACP Management

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#125]
Create Jira Software v7 Docker Image for deployment on ACP/DSP Kube8 cluster.
 
Docker image repo:
https://gitlab.digital.homeoffice.gov.uk/docker/docker-jira/blob/master/Dockerfile

k8s deployment 
https://gitlab.digital.homeoffice.gov.uk/Devops/kube-jira/tree/master

- [x] Create Jira Software v7 Docker Image 
- [x] deploy to management not prod
- [ ] deploy to management prod
- [x] fix lets encrypt
- [ ] request pvc ebs volume is backed up (acp bau ticket) with retention period set
- [x] test migrate db + content
- [ ] test backup recovery

**Comment by chrisns** [comment]
to add to description - sighted repos describe Jira <= v6.4.13-1

**Comment by tomfitzherbert** [comment]
Fixed routing/port issues by updating the `server.xml`.
Successfully restored a backup from dq-dev JIRA.
Will need to extract `attachments` and `avatars` for the prod migration.

**Comment by tomfitzherbert** [comment]
Next step is to work out how to migrate the existing users that are managed by the LDAP Connector connection to the DEV AD. May be able to swap out for a Keycloak realm but need to test this before proceeding. Otherwise will need to switch to local JIRA directory for user management.

**Comment by chrisns** [comment]
https://www.miniorange.com/step-by-step-guide-to-set-up-jboss-keycloak-as-idp-for-jira

**Comment by chrisns** [comment]
https://marketplace.atlassian.com/plugins/com.bitium.jira.SAML2PluginJira/server/overview
https://github.com/bitium/jira-saml-plugin

**Comment by cassidti** [comment]
MTY
