### ISSUE TITLE
Configure Bastion Host Linux connectivity tests

### ISSUE THREAD

**Issue by nick-otter** [UKHomeOffice/dq-aws-migration#134]
## Description:

Having made commits (see **List of Commits**) to repos [internal tableau](https://github.com/UKHomeOffice/dq-tf-external-tableau), [external tableau](https://github.com/UKHomeOffice/dq-tf-internal-tableau) and [dq-tf-ops](https://github.com/UKHomeOffice/dq-tf-ops), ensure the Bastion Host Linux instance now displays no connectivity test failures in CloudWatch.

List of Commits:
* [removing duplicate var in connectivity test](https://github.com/UKHomeOffice/dq-tf-external-tableau/commit/834134afa5e26e0f73c791b16e7b740259c00ee1)
* [removing duplicate var in connectivity test](https://github.com/UKHomeOffice/dq-tf-internal-tableau/commit/420dc540afdf729ec4c0edc28553e5aca5b5c264)
* [added listening check to bastion host linux](https://github.com/UKHomeOffice/dq-tf-ops/commit/49752b22f1eb1f2a24784eb2bdc4428a875f6ec2)
* [added BDM RDS db ip to ops](https://github.com/UKHomeOffice/dq-tf-infra/commit/b4d5cd20c842fa75a91090a39a66f013ceacc0bb)

## Acceptance criteria:
- [x] Bastion Host Linux instance shows no connectivity test failures in CloudWatch

**Comment by david-wirelab** [comment]
Found root cause of the issue. 
Fix pending on DNS helper deploy across Apps/Ops VPC. https://github.com/UKHomeOffice/dq-tf-ops/pull/29 and https://github.com/UKHomeOffice/dq-tf-apps/pull/23

**Comment by nick-otter** [comment]
blocked by https://github.com/UKHomeOffice/dq-aws-transition/issues/137

**Comment by david-wirelab** [comment]
All 4 checks are passing on the Linux instance and there are no failures.
