### ISSUE TITLE
Cloudwatch monitoring is not showing all machines

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#137]
Issue seems intermittent. Some EC2 instances are not showing up in the ConnectivityTester metrics or within logs however they are reporting in default values successfully.

**Comment by nick-otter** [comment]
Raised but not resolved with AWS Support on 18/12/2017: [case link](https://console.aws.amazon.com/support/v1?region=eu-west-2#/case/?displayId=4742893891&language=en) (requires role permission to view)

**Comment by david-wirelab** [comment]
Issue is caused by MS AD and the DNS server it sets up by default.
Ops and Apps VPC are peered with AD and get their DHCP options for DNS from AD  which are the AD servers 2 IPv4 addresses. This VPC has no IGW and wouldn't know about the outside world.
Errors on instances within the affected VPCs: 
``` EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.eu-west-2.amazonaws.com/"```

Tried changing the DNS servers on the connectivity testers - root pwd not known.

Added GoogleDNS as a secondary DNS server for AD however setting has not been propagated down from AD to the peered VPCs (no error message - perhaps list variable within list won't work?)

```# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.99.1.239
nameserver 10.99.2.132```

**Comment by david-wirelab** [comment]
Found root case - AD module did not turn on route table and subnet association.

**Comment by david-wirelab** [comment]
Solution was adding GoogleDNS as secondary providers. It seemed to take a very long time 3+ hours at least for this change to take effect in AWS land.
