### ISSUE TITLE
Update AWS Enterprise Support on Accounts (post Go-Live)

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#142]
When cutting over to AWS DQ Services post-transition project, we need to keep/review/remove AWS Enterprise Support where not required:

Proposed:
- Prod = Keep
- Not-Prod = Remove
- CI = Review (decision to extend for 1 month post go-live)
- Mock = Remove

- [ ] Remove AWS Enterprise Support from accounts not requiring this level of support

**Comment by chrisns** [comment]
isn't this post go-live not pre?

**Comment by cassidti** [comment]
yep, changed

**Comment by cassidti** [comment]
MTY
