### ISSUE TITLE
PSQL RDS instance is not accepting connections from Connectivity Tester

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#144]
Due: 04/01

RDS instance is not responding on open port. Needs further investigation.
Checks to be carried out:
- [x]  Verify RDS PostgreSQL Security Group has the correct ingress CIDR ranges
- [x]  Mock a connectivity tester listening on port 5432 in the same subnet and Security Group (SG) as the RDS instance and check connectivity to it to verify intra subnet and SG settings
- [x] AWS Support investigation
- [ ] Update Connectivity Tester config with RDS request exceptions

**Comment by nick-otter** [comment]
AWS Support Ticket: 
[Can't get to PostgreSQL on port 5432](https://console.aws.amazon.com/support/v1?region=eu-west-2#/case/?displayId=4754469751&language=en)

Links AWS Support supplied to investigate:
[Accessing PostgreSQL databases...](https://www.linkedin.com/pulse/accessing-postgresql-databases-from-aws-python-lambda-wang/)
[Accessing RDS PostgreSQL...](https://medium.com/@dominicwong617/accessing-rds-postgresql-from-aws-lambda-using-node-js-6c5ea4eea3f7)

**Comment by david-wirelab** [comment]
Upon investigation it was found routing and SG were all ok. Both testers can get to RDS using netcat: 
OPS
xxx@ip-10-2-0-12:~$ nc -zv terraform-xxxxxx.xxxxxx.eu-west-2.rds.amazonaws.com 5432
Connection to terraform-xxxxxx.xxxxxx.eu-west-2.rds.amazonaws.com 5432 port [tcp/postgresql] succeeded!

BDM
xxx@ip-10-1-10-11:~$ nc -zv terraform-xxxxxx.xxxxxx.eu-west-2.rds.amazonaws.com 5432
Connection to terraform-xxxxxx.xxxxxx.eu-west-2.rds.amazonaws.com 5432 port [tcp/postgresql] succeeded!

AWS confirmed RDS does not accept all connections eg. ICMP is blocked outright along with other types of TCP socket calls. They advised to redo the TCP socket caller config so RDS can accept requests from the connectivity tester. 
There's no official AWS documentation describing limitations at present (22/12/2017).

**Comment by nick-otter** [comment]
The RDS instance is currently accepting connections and its connectivity tests now show no failures.

No code changes have taken place, so we are assuming AWS made changes to how RDS works.

Further actions: 
- [x] Freeze code change for this card
- [x] Check again 03/01

**Update:** RDS instance not accepting connections on 03/01, continuing on with actions above.

**Comment by nick-otter** [comment]
Blocked: https://github.com/UKHomeOffice/dq-aws-transition/issues/153

**Comment by david-wirelab** [comment]
#153 resolved. Closing issue.

**Comment by david-wirelab** [comment]
Cause:
TF configuration inconsistence causing route to AD DNS server getting removed. Connectivity testers only doing an NSLOOKUP on the primary DNS and then quit checking the rest.
Solution:
Fixing TF config by not using a mix of in-line route table routes and route resources so routes to AD VPC don't get removed.
Suggestion:
Update Go config so it does an NSLOOKUP on secondary DNS server should first go down.
