### ISSUE TITLE
Make a encrypted EC2 instance with an encrypted boot volume

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#146]
- [x] Launch connectivity-tester and create a local image
- [x] aws copy-image --encrypted ${connectivity-tester-ami} with PROD account
- [x] start a representative instance with the new encrypted AMI
- [x] repeat step 1 for notprod + mocks and CI
- [x] destroy step 2
- [x] modify terraform `connectivity-tester-tf` to look for an AMI local to the account "self"

**Comment by david-wirelab** [comment]
AMI is public - copying a Public AMI is not supported by AWS: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/CopyingAMIs.html
The owner of the AMI however can copy it to other accounts.

**Comment by david-wirelab** [comment]
Blocked by https://github.com/UKHomeOffice/dq-aws-transition/issues/70

**Comment by david-wirelab** [comment]
Images deployed.
