### ISSUE TITLE
Route to AD VPC disappear from Ops and Apps route table

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#153]
After some time the route to gets removed by something and gets redeployed every time when infra runs a deploy on master.

**Comment by chrisns** [comment]
Issue is described here: https://www.terraform.io/docs/providers/aws/r/route.html#inner because we have a combination of routes defined in `route table` resources and in `route` resources

**Comment by david-wirelab** [comment]
Fix pushed - pending on infra @ master rebuild.
