### ISSUE TITLE
Setup Cloudwatch log stream to S3

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#157]
- [x] Investigate options available in eu-west-2 region for log delivery
    - [x] Kinesis
    - [x] Kinesis Firehose (not available)
    - [x] Export from Cloudwatch using AWS CLI
    - [x] Lambda functions
- [x] Select and evaluate options
    - [x] Lambda function with boto3 `s3.create_export_task`
- [x] Check IAM roles and policies and test in console
- [x] Create test function in console
- [ ] Destroy test resources
- [x] TF it
  - [ ] Create repo for module
  - [x] 3x Build Lambda function and permission
  - [x] 3x Create role and policy
  - [x] 3x Create CW event targets and rule
  - [x] Create deployment package for each log set
  - [x] Swap in vars
  - [x] Add IAM permissions to interact with Lambda
  - [ ] Deploy all to infra
      - [ ]  have a drone build step that does deployment zipping prior to terraform running
      - [ ] bucket names ingested from main TF
      - [ ] parameterize log name
       - [ ] 1x unit test
       - [x] python code should be linted
       - [x] 3x `aws_cloudwatch_event_rule` one for each Lambda function
       - [x] alerts put in place for when the Lambda fails.
  - [ ] Deploy to Prod/Nonprod
- [ ] Confirm logs are being shipped according to schedule to their named folders

**Comment by david-wirelab** [comment]
Only one export task can run at a time per account. Need doing a lambda function for each log group.

**Comment by cassidti** [comment]
MTY
