### ISSUE TITLE
Re-Deploy Greenplum Cluster for Consultancy

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#159]
Launch EC2 cluster for Greenplum Consultancy

- [x] Public SSH Key received
- [x] Cluster Deployed in separate account
- [x] IP Addresses provided to consultancy

**Comment by chrisns** [comment]
blocked waiting for pub ssh key

**Comment by cassidti** [comment]
@chrisns Justing checking whether swap is on EBS on not
