### ISSUE TITLE
Inventory Data Ingest Server - WFTP01

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#167]
Due: 12/01

Document server configuration.

- [x] Get OS and resources
- [x] Get FTP/SFTP make and version 
- [x] Get ODBC details
- [x] Get any keys
- [x] Get Python version
- [x] Check for custom monitoring setup
- [x] Check scheduled tasks/crontab
- [x] Check local users/groups and passwords
- [x] Check directory structure
- [x] Check what data needs migrated
- [x] Check jobs
    - [x] job1
    - [ ] job2
- [x] Check local scripts
    - [x] Compare scripts on Gitlab and servers and note differences
      - [x] script1
      - [x] script2
- [x] Note anything else

### Acceptance criteria

- [x] All the above completed

**Comment by cassidti** [comment]
All tasks completed and information gathered to inform server build and application/script.
