### ISSUE TITLE
Inventory Data Archive - FLS01

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#170]
Due: 12/01

Document server configuration.

- [x] Get OS and resources
- [x] Get FTP/SFTP make and version 
- [x] Check for custom monitoring setup
- [x] Check scheduled tasks/crontab
- [x] Check directory structure
- [x] Check jobs
    - [ ] job1
    - [ ] job2
- [x] Check local scripts
    - [ ] Compare scripts on Gitlab and servers and note differences
      - [ ] script1
      - [ ] script2
- [x] Note anything else

### Acceptance criteria

- [x] All the above completed

**Comment by cassidti** [comment]
Inventory complete
