### ISSUE TITLE
Inventory int dashboard - TAB03

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#172]
Document server configuration.

- [x] Get dashboard, SQL version
- [x] Get software
- [x] Check for custom monitoring setup
- [x] Check scheduled tasks/crontab
- [x] Check local users/groups
- [x] Check directory structure
- [x] Check jobs
- [x] Note anything else

### Acceptance criteria

- [x] All the above completed

**Comment by cassidti** [comment]
Uploaded to TAB03 in install media bucket (NotProd)
