### ISSUE TITLE
GA app in DQ ACP not-prod APP

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#180]
Migrate GA application from DSP to ACP Not-Prod environment for development of the application to continue.

## Acceptance Criteria
- [x] Docker images deployed to ACP Not-Prod
- [x] Other AWS Services (RDS, Elasticache)
- [x] GA Landing S3 bucket created
- [x] Developers have access

**Comment by cassidti** [comment]
Need GA Landing S3 bucket in ACP ticket

**Comment by tomfitzherbert** [comment]
Confirmed with James that team is now self sufficient in ACP
