### ISSUE TITLE
CRT in DQ ACP not-prod APP

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#181]
Migrate CRT application from DSP to ACP Not-Prod environment for development of the application to continue.

## Acceptance Criteria
- [x] Jira on Docker
- [x] Docker image deployed to ACP Not-Prod
- [x] Developers have access

**Comment by cassidti** [comment]
CRT ineeds JIRA Datacentre version wanting a shared read/write disk and ACP don't have a way to deploy EFS back PVCs yet

**Comment by tomfitzherbert** [comment]
Evan has not completed the Data Centre version so I have removed that from scope. The continuation will be picked up by the Yellow team post Transition.
