### ISSUE TITLE
Add Placement Group for GPDB instances

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#199]
Add Placement Group for GPDB instances

- [ ] Terraform Scripts updated

**Comment by cassidti** [comment]
I guess this is done with latest deploy?

**Comment by cassidti** [comment]
Included in #159

**Comment by chrisns** [comment]
we need to make a seperate ticket(s) to describe ingesting what the consultancy do and replicating it in-situ in the dq-apps VPC which will include updating our infra code
