### ISSUE TITLE
Open Source api-test-data-generator Repository

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#211]
Analyse, convert and migrate repository to GitHub (https://github.com/topics/hodq)

- [x] Refactor/Desensitize Code
- [ ] Approval to Open Source
- [x] Create Git Hib Repo
- [x] Migrate/commit code

**Comment by chrisns** [comment]
https://github.com/UKHomeOffice/dq_api-test-data-generator
