### ISSUE TITLE
Open Source nats-sftp-dmz Repository

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#215]
Analyse, convert and migrate repository to GitHub (https://github.com/topics/hodq)

- [x] Refactor/Desensitize Code
- [x] Approval to Open Source
- [x] Create Git Hib Repo
- [x] Migrate/commit code

**Comment by chrisns** [comment]
https://github.com/UKHomeOffice/dq_sftp-nats-dmz

**Comment by tomfitzherbert** [comment]
This repo is now open source.
