### ISSUE TITLE
Create Lambda - S3 Landing Parsed files to S3 GA

### ISSUE THREAD

**Issue by nick-otter** [UKHomeOffice/dq-aws-migration#230]
Due Date:
Repo:

Pre requisites:
   - [ ] Create S3 GA in ACP

## Acceptance Criteria 
- [ ] all PARSED files copied to S3 GA and then deleted

**Comment by chrisns** [comment]
may not need to be Lambda, a replication rule on the S3 bucket may suffice

**Comment by chrisns** [comment]
will need to consider https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-what-is-isnot-replicated.html and make sure that DELETEs are not replicated
