### ISSUE TITLE
Inventory OAG Processing

### ISSUE THREAD

**Issue by nick-otter** [UKHomeOffice/dq-aws-migration#233]
Document server configuration.

- [x] Get Python version
- [ ] Check for custom monitoring setup
- [x] Check scheduled tasks/crontab
- [x] Check local users/groups
- [ ] Check directory structure
- [x] Check jobs
    - [x] job1
    - [x] job2
- [x] Check local scripts
    - [x] Compare scripts on Gitlab and servers and note differences
      - [x] script1
      - [x] script2
- [x] Note anything else

### Acceptance criteria

- [x] All the above completed

**Comment by cassidti** [comment]
E2E OAG Process Captured
New Issues raised
