### ISSUE TITLE
No Put permissions on GA Buckets in ACP

### ISSUE THREAD

**Issue by nick-otter** [UKHomeOffice/dq-aws-migration#234]
Request into ACP for ensuring the GA buckets have PUT permissions.
https://github.com/UKHomeOffice/application-container-platform-bau/issues/2695

- [x] Keys for NotProd GA Landing Bucket (dq-apps-notprod-gait-s3) have List and Put permissions
- [x] Keys for Prod GA Landing Bucket (dq-apps-gait-s3) have List and Put permissions

**Comment by chrisns** [comment]
request raised https://github.com/UKHomeOffice/application-container-platform-bau/issues/2601

**Comment by nick-otter** [comment]
all actions denied, confirm bucket name with Tasharn

**Comment by nick-otter** [comment]
name: `dq-apps-prod-gait-s3` / `dq-apps-notprod-gait-s3`

**Comment by nick-otter** [comment]
facing: ` when calling the PutObject operation: Access Denied` error

**Comment by chrisns** [comment]
raised with ACP team

**Comment by chrisns** [comment]
```
AWS_ACCESS_KEY_ID=xx AWS_SECRET_ACCESS_KEY=xx aws s3 cp --sse aws:kms /Users/cns/Desktop/pubkey.asc s3://dq-apps-notprod-gait-s3/file
upload: Desktop/pubkey.asc to s3://dq-apps-notprod-gait-s3/file   
```
works just fine, tested with prod+not prod creds
