### ISSUE TITLE
Open Source dq_wherescape_scripts Repository

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#240]
Analyse, convert and migrate repository to GitHub (https://github.com/topics/hodq)

- [x] Refactor/Desensitize Code
- [x] Approval to Open Source
- [x] Create Git Hib Repo
- [x] Migrate/commit code

**Comment by chrisns** [comment]
https://github.com/UKHomeOffice/dq_wherescape_scripts

**Comment by tomfitzherbert** [comment]
Reviewed, approved and made public.
