### ISSUE TITLE
ITHC access assistance

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#250]
## responses/resolutions to the following points raised:

- [x] Linux: do I need to upload my SSH private key and use that identity? (server doesn’t seem to support password auth )
 
- [x] Trying login with given username and putty.
 
- [x] master-1-apps-prod-dq 25.101 – “no supported authentication methods available ( server sent pubkey, gssapi-keyex, gsssapi-with-mic )”
 
- [x] linux-instance-dataingest-apps-prod-dq 6.200 – same as above
 
- [x] Windows: do I need to be added to the local admin user group ?
 
- [x] ec2-win-dataingest-apps-prod-dq 6.100 - user account is not authorized for remote login (from mstsc)
 
- [x] wherescape-data-pipeline-apps-prod-dq 8.100 - same 
 
- [x] ~~instance-external-tableau-apps-prod-dq 14.11 – same~~

**Comment by david-wirelab** [comment]
instance-external-tableau-apps-prod-dq is a mock machine - no need to login

**Comment by david-wirelab** [comment]
Added both ITHC users to local admins via GPO - tested RDP login worked for both accounts, no error message.

**Comment by chrisns** [comment]
thanks @david-wirelab
