### ISSUE TITLE
S4 Test Files

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#252]
Need a number of S4 Test files in the Pre-Production Landing S3 Bucket of all types to test Data Ingest and Data Pipeline.

## Acceptance Criteria
- [ ] RAW test files in Pre-Prod
- [ ] STORED test files in Pre-Prod
- [ ] PARSED test files in Pre-Prod
- [ ] FAILED test files in Pre-Prod

**Comment by ianrelf** [comment]
I spoke to Phil Hibis - he says that the Test File Generator only creates PARSED S4 files. Apparently, there is a CR in the backlog to enhance the generator to generate corresponding RAW files.

I spoke to Ray Hayhurst - he will dig out some S4 test files for me.

**Comment by ianrelf** [comment]
I now have the files (from Ray).
I need help to be able to put them somewhere (anywhere).

**Comment by ianrelf** [comment]
I have requested AWS access.

**Comment by cassidti** [comment]
Test Files uploaded to NP
