### ISSUE TITLE
DQ S3 Configurations

### ISSUE THREAD

**Issue by nick-otter** [UKHomeOffice/dq-aws-migration#255]
Due date:
Repo:

- [x] `S3  Landing` Directory Structure: 
```
(/ = top dirs) 
/acl
/nats
/oag
/s4
```
- [x] `S3 Archive` Directory Structure: 
```
/acl = >
           <YYYYMMDD>
/nats = > 
           <YYYYMMDD>
/oag = >
            <YYYYMMDD>
/s4 = >
          failed =>
                   <YYYYMMDD>
          parsed = >
                   <YYYYMMDD>
          raw = >
                   <YYYYMMDD>
          stored = >
                   <YYYYMMDD>
```

## Acceptance Criteria 
- [x] `S3 Landing` Directory Structure as above.
- [x] `S3 Archive` Directory Structure as above.

**Comment by nick-otter** [comment]
blocked: https://github.com/UKHomeOffice/dq-aws-transition/issues/253

**Comment by david-wirelab** [comment]
done in prod and notprod
