### ISSUE TITLE
Add OAG scripts to SSM Ingest Repo

### ISSUE THREAD

**Issue by nick-otter** [UKHomeOffice/dq-aws-migration#258]
Due Date:
Repo: https://github.com/UKHomeOffice/dq-ssm_ingest

- [x] Add additional OAG scripts to repo
- [ ] Check additional OAG scripts with Tom or Chris

## Acceptance Criteria
- [ ] DQ SSM Ingest repo has all OAG scripts

**Comment by AramSimonian** [comment]
Went through the files referenced within 00201SG1LFTP01.crontab  &  00213SG1LEXT01.crontab files and found OAG files that weren't in the repo (https://github.com/UKHomeOffice/dq-ssm_ingest):
 - /ADT/scripts/oag_house_keeping.sh
 - /NATS/scripts/sftp_nats_client_maytech.py

They are now added to EXT_Server and WEB_Server folders respectively.
