### ISSUE TITLE
SQL Server to Postgres migration

### ISSUE THREAD

**Issue by AramSimonian** [UKHomeOffice/dq-aws-migration#273]
Some views are to be migrated from SQL Server to Postgres, where they will be tables instead.

I have identified the following points:
 - [x] translating datatypes between SS & PG
 - [ ] checking supported datatypes within BDM
 - [ ] formatting of the CREATE statement for PG
 - [ ] table constraints / auto-increment columns, etc.
 - [ ] data transfer

**Comment by cassidti** [comment]
MTY
