### ISSUE TITLE
Get WS working with local and remote scripts

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#276]
- [x] Job_10_NRT
- [x] Job_10_Bulk > redundant
- [x] Job_13_poav
- [x] Job_15_Field_level
- [x] Job_15_subset_final
- [x] Job_15_subset_process
- [x] Job_20
- [ ] Job_21 / err: OSError: [Errno 2] No such file or directory
- [x] Job_21a
- [ ] Job_22 / err: OSError: [Errno 2] No such file or directory
- [x] Job_22a
- [ ] Job_23 / err: cannot EXECUTE a null querystring / Need RAW data
- [x] Job_24
- [ ] Job_25 / err: OSError: [Errno 2] No such file or directory
- [ ] Job_25a / err: Batch file returned an error code of 3
- [ ] Job_26 / err: OSError: [Errno 2] No such file or directory
- [ ] Job_26a / err: Batch file returned an error code of 3
- [x] Job_27
- [ ] Job_28 / err: Invalid object name WSARC.dbo.archive_ws_wrk_audit_log
- [x] Job_29a
- [x] Job_29b
- [x] Job_29c
- [x] Job_29d
- [x] Job_29e
- [x] Job_29f
- [x] Job_29g
- [x] Job_29h
- [x] Job_29i
- [x] Job_40_RPT_EXT
- [x] Job_30_RPT_INT
- [x] Job_33
- [x] Job_35_loop
- [x] Job_35_single
- [x] Job_50_SSM
- [x] Job_50_SSM_Backlog  - not in use
- [x] Job_55 
- [ ] Job_58  / err: Batch file returned an error code of 3
- [x] Job_60_NBTC_FMS
- [x] Job_61
- [x] Job_62
- [x] Job_70 - Not in use
- [x] Job_80_Backup
- [x] Job_90
- [x] Job_95_Truncate_NRT
- [x] Job_95_Truncate_Mart_External
- [ ] Job_120 / err: No such file or directory
- [ ] Job_126 / err: Batch file returned an error code of 3

**Comment by david-wirelab** [comment]
- [x] Job10 fixed by editing the offending table name in the baseline text and re-applying it.

**Comment by cassidti** [comment]
MTY
