### ISSUE TITLE
Update Data Transfer App to Support Encrypt/Decrypt on Put/Get

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#277]
Update to Data Transfer App required to support additional parameters around KMS etc in S3 bucket requests.
https://github.com/UKHomeOffice/dq-aws-transition/issues/234#issuecomment-366643429

- [ ] Data Transfer App updated

**Comment by tomfitzherbert** [comment]
See https://github.com/UKHomeOffice/data-transfer/pull/18
