### ISSUE TITLE
Create Keycloak Realms per DQ User Group

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#288]
Create Keycloak Realms per DQ User Group

Realms
  - [x] Carrier Portal Prod (o365 + Local)
  - [x] Carrier Portal Not-Prod (o365 + POISE)
  - [x] GAIT Prod (o365 + POISE)
  - [x] GAIT Not-Prod (o365 + POISE)
  - [x] CRT Prod (o365 + POISE)
  - [x] CRT Not-Prod (o365 + POISE)
  - [x] BDM Prod (o365 + POISE)
  - [x] BDM Not-Prod (o365 + POISE)
  - [x] Internal Dashboard Prod (o365 + POISE)
  - [x] Internal Dashboard Not-Prod (o365 + POISE)

**Comment by chrisns** [comment]
https://github.com/UKHomeOffice/application-container-platform-bau/issues/2738

**Comment by chrisns** [comment]
done, though no POISE
