### ISSUE TITLE
Configure Maytech Mock Connectivity from NotProd Ingest Linux Server

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#300]
Private Key Migration
- [x] Private Key for Linux Ingest NotProd (/home/SSM/.ssh/id_rsa) for Mock Maytech Server 

Configure NotProd ssh_remote_* parameters in sftp_oag_client_maytech.py
- [x] ssh_remote_host: <mock SFTP server> 
- [x] ssh_remote_user: <mock oag user>
- [x] ssh_remote_key: /home/SSM/.ssh/id_rsa

**Comment by nick-otter** [comment]
Path for private key for mock server `35.178.28.118` is `/home/wherescape/id_rsa`

**Comment by nick-otter** [comment]
- [x] update `sftp_oag_client_maytech.py` to access environment variables
- [x] add `oag` values to parameter store
- [x] update linux user data 
- [x] update linux IAM policy

**Comment by nick-otter** [comment]
parameter names: `maytech_host`, `maytech_user`
