### ISSUE TITLE
Configure Maytech Prod Connectivity from Prod Ingest Linux Server

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#301]
Private Key Migration
- [x] Private Key from Pre-Prod DMZ Server (pre-prod) put on Linux Ingest Prod (/home/SSM/.ssh/id_rsa)

Configure Prod ssh_remote_* parameters in sftp_oag_client_maytech.py
- [x] ssh_remote_host: <See Word Doc> 
- [x] ssh_remote_user: <See Word Doc>
- [x] ssh_remote_key: <See Word Doc>

**Comment by nick-otter** [comment]
parameter names: `maytech_host`, `maytech_user`

**Comment by nick-otter** [comment]
path for ssh remote key is `/home/wherescape/maytech_preprod_id_rsa`
