### ISSUE TITLE
Update MVT Database Creds in OAG Python scripts

### ISSUE THREAD

**Issue by AramSimonian** [UKHomeOffice/dq-aws-migration#304]
Update MVT Database Creds in OAG Python scripts
 - [x] dp2_oag.sh
 - [x] dp4_ssm.sh

**Comment by nick-otter** [comment]
Scripts found in `/ssm-ingest/ADT/EXT_server`

**Comment by nick-otter** [comment]
Waiting on image build for scripts to be pulled in
