### ISSUE TITLE
Setup Putty Saved Sessions for SSM processing on Pre-Prod Data Pipeline Server

### ISSUE THREAD

**Issue by AramSimonian** [UKHomeOffice/dq-aws-migration#305]
Setup Putty Saved Sessions for SSM processing on Pre-Prod Data Pipeline Server
 - [ ] Generate Data Ingest Linux key for WSR server saved Putty session: ***ssm_ssh_login***
 - [ ] Generate Data Ingest Linux key for WSR server saved Putty session: ***nats_ssh_login***
 - [ ] Generate Greenplum key for WSR server saved Putty session: ***greenplum_ssh_login***

**Comment by david-wirelab** [comment]
Closing Dupe of: https://github.com/UKHomeOffice/dq-aws-transition/issues/330
https://github.com/UKHomeOffice/dq-aws-transition/issues/329
