### ISSUE TITLE
Add data-transfer job for OAG data to S3 archive

### ISSUE THREAD

**Issue by AramSimonian** [UKHomeOffice/dq-aws-migration#309]
Add Data Transfer job for OAG data to S3 archive.

Pre requisites: 
- [x] `sftp_oag_client_maytech.py` downloads files successfully.

## Acceptance Criteria
- [x] PM2 logs show no errors for OAG to S3 Archive configuration
- [x] OAG data is moved to S3 Archive bucket
- [x] Data Transfer configuration repeats

**Comment by nick-otter** [comment]
All Data Transfer configurations not working despite working yesterday.

Assume not picking up `envs`.

- [x] Switch log level to debug in ecosystem
- [x] Remove additional configurations and test
