### ISSUE TITLE
Request Digital Account for ITHC3 tester for VPN access

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#331]
Request Digital Account for ITHC3 tester so they can access DQ AWS resources using Prod VPN

- [x] Request sent and verified by ITHC tester
- [x] Digital Account provided DQ Prod VPN profile

**Comment by chrisns** [comment]
https://github.com/UKHomeOffice/application-container-platform-bau/issues/2764

**Comment by chrisns** [comment]
waiting on confirmation that they have necessary vpn profiles
