### ISSUE TITLE
Setup ITHC PenTest EC2 Instances

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#333]
Setup ITHC PenTest EC2 Instances.

- [x] Instances Setup

**Comment by chrisns** [comment]
## Kali
- 10.1.8.44
- 10.1.26.249
- 10.1.4.49
- 10.1.12.132
- 10.1.6.112
- 10.1.14.81

## Windows
- 10.1.8.34
- 10.1.26.161
- 10.1.4.213
- 10.1.12.180
- 10.1.6.244
- 10.1.14.14

All accessible from prod bastions

**Comment by chrisns** [comment]
needs to be redone with new pen tester's creds

**Comment by chrisns** [comment]
rebuilt, updated above ips
