### ISSUE TITLE
GP Timezone config needed for NotProd/Prod

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#350]
``#timezone_abbreviations = 'Default``

**Comment by cassidti** [comment]
Action:

1. Rename Default file to Default_Original in /usr/local/greenplum-db-4.3.4.1/share/postgresql/timezonesets
2. Restart Greenplum gpstop/gpstart
3. Create new Default file and set gpadmin:gpadmin 664 permissions

NB: Automation issue raised: https://github.com/UKHomeOffice/dq-aws-transition/issues/355
