### ISSUE TITLE
Test End-to-End load of S4 PARSED files from DQ Landing to Greenplum rpt_internal/rpt_external

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#361]
Test End-to-End load of S4 PARSED files from DQ Landing to Greenplum rpt_internal/rpt_external, ensuring all jobs succeed and record timings.

- [x] Turn On Data Transfer (S3 Landing to Data Ingest Win) on Data Ingest Windows
  - [x] Record time taken to get all files into local directories
- [x] Run Sequence Check script against local files
  - [x] Record time taken to get all files into local directories
- [x] Run Job_10_NRT > Job_13_poav_level… > Job_15_Field_Level_KPI
  - [x] Record time taken per job	
- [x] Run Job_60_NBTC_FMS
   - [x] Record time taken per job
- [x] Run Job_30_INT
   - [x] Record time taken per job
- [x] Run Job_40_EXT
   - [x] Record time taken per job
- [x] Run Job_80_Backup…
   - [x] Record time taken per job

**Comment by david-wirelab** [comment]
Job_60 needs re-run as it had no SSM data.
