### ISSUE TITLE
Get additional MVT reference from Prod Sungard

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#369]
- [x] Insert statements provided and inserted into AWS NotProd and Prod MVT

**Comment by AramSimonian** [comment]
These tables are affected by INSERT INTO:
acl_schd   acl.py, 23
schd   schd.py, 92;  oag.py, 186
oag_flight   oag.py, 28
oag_carrier   oag.py, 48
oag_leg   oag.py, 65
oag_files   oag.py, 447

These tables are affected by UPDATE:
history   acl.py, 227; oag.py, 180
acl_csv   acl.py, 233; schd.py, 86
