### ISSUE TITLE
Investigate WSR Jobs - No Indexes to Pre-drop error

### ISSUE THREAD

**Issue by cassidti** [UKHomeOffice/dq-aws-migration#371]

**Comment by david-wirelab** [comment]
- [x] Change index count from 500k to 100k
- [x] Run 2 days worth of archive data overnight
- [x] Check results
Lowering the metric of indexes processed from 500k to 100k seems to have eased the pressure of the DB - only one error of this type on Job_30.

New error message: `deadlock detected`
