### ISSUE TITLE
OPS VPC

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#52]
- [x] 2 x ec2 (open on ssh & RDP) 
- [x] 2 x security groups
- [x] 1 x acl
- [x] 1 x subnet
- [x] Peering setup
- [x] Peering with external VPC
- [x] 1 x S3 endpoint

**Comment by david-wirelab** [comment]
Updated output and variable files. Added tags to the bastion hosts. Updated tests accordingly.
