### ISSUE TITLE
Peering VPC

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#55]
- [x] 1 x ec2 haproxy
- [x] 1 x ec2 connectivity tester
- [x] 2 x subnets
- [x] 2 x security groups
- [x] all the peering
- [x] 1 x s3 bucket + IAM policies

**Comment by david-wirelab** [comment]
To investigate: cidr_block only takes one entry at a time for ACL. Ideally need passing them as a list.

**Comment by david-wirelab** [comment]
Configured VPC with Connectivity tester module.
Configured peering module in infra.
Setup output files, route tables and updated other VPC so Peering can establish peering and accept connection from OPS, ACP subnets.
