### ISSUE TITLE
mock data pipeline

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#64]
- [x] 1 x ec2 representing postgres
- [x] 1 x ec2 representing a webserver
- [x] 1 x private subnet
- [x] 2 x security group
- [x] Added to dq-tf-apps

**Comment by david-wirelab** [comment]
Build complete. Submitted for peer review.

**Comment by david-wirelab** [comment]
Added to repo, ready for deploy.
