### ISSUE TITLE
DQ Apps VPC

### ISSUE THREAD

**Issue by david-wirelab** [UKHomeOffice/dq-aws-migration#78]
- [x] 8 x subnets
- [ ] 16 x security groups
- [ ] Peering
- [x] 1 x NAT GW
- [x] 1 x EIP
- [ ] 8 x Route Tables
- [x] 1x IGW

**Comment by david-wirelab** [comment]
Repo required.

**Comment by chrisns** [comment]
superseded by updated A/Cs in #57
