### ISSUE TITLE
Apply naming and tagging scheme across all infra

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#85]
See https://github.com/UKHomeOffice/dq-tf-ops/pull/2 conversation for examples.

## [Dq Tf Ops](https://github.com/UKHomeOffice/dq-tf-ops)
- [x] ad_instance.tf
- [x] instances.tf
- [x] vpc.tf
- [x] update tests
- [x] clean up, delete unused vars in ops

## [Dq Tf Apps](https://github.com/UKHomeOffice/dq-tf-apps)
- [x] main.tf (excluding individual apps)
- [x] ad_instance.tf
- [x] s3.tf
- [x] update tests
- [x] main.tf (excl. individual apps)
- [x] clean up, delete unused vars (excl. name prefix)
- [x] update az vars
- [x] main.tf (incl. individual apps)
- [x] clean up, delete unused vars (incl. name prefix)

## [BDM](https://github.com/UKHomeOffice/dq-tf-business-data-manager)
- [x] main.tf
- [x] clean up, delete unused vars

## [External Tableau](https://github.com/UKHomeOffice/dq-tf-external-tableau)
- [x] main.tf
- [x] clean up, delete unused vars

## [Internal Tableau](https://github.com/UKHomeOffice/dq-tf-internal-tableau)
- [x] main.tf
- [x] clean up, delete unused vars

## [Data Feeds](https://github.com/UKHomeOffice/dq-tf-datafeeds)
- [x] main.tf
- [x] clean up, delete unused vars

## [Data Ingest](https://github.com/UKHomeOffice/dq-tf-dataingest)
- [x] main.tf
- [x] clean up, delete unused vars

## [Data Pipeline](https://github.com/UKHomeOffice/dq-tf-datapipeline)
- [x] main.tf
- [x] clean up, delete unused vars

## [Gpdb](https://github.com/UKHomeOffice/dq-tf-gpdb)
- [x] main.tf
- [x] clean up, delete unused vars

## [Peering](https://github.com/UKHomeOffice/dq-tf-peering)
- [x] main.tf
- [x] clean up, delete unused vars

## [Mock Acp](https://github.com/UKHomeOffice/dq-tf-mock-acp/)
- [x] main.tf
- [x] clean up, delete unused vars

## [Infra](https://github.com/UKHomeOffice/dq-tf-infra/)
- [x] delete unused vars and update with new vars for each module

## [Peering Haproxy](https://github.com/UKHomeOffice/dq-tf-peering-haproxy)
- [x] main.tf
- [x] clean up, delete unused vars

**Comment by nick-otter** [comment]
There is a pending build standards doc which references tagging:

https://github.com/UKHomeOffice/technical-service-requirements/pull/20
